### ISSUE TITLE
Deleted lines not really deleted

### ISSUE THREAD

**Issue by kenan-rhoton** [marcusbuffett/chess-trainer-site#5]
It seems that if you decide to change a line in your openings preparation (for example if I decide to switch my response to 1. e4 e5 from 2. f4 to 2. Nf3), despite a message warning that my old lines will get deleted, they don't, which means they'll both still show up in both reviews (which is annoying because I have to then input outdated answers for my preparation) and in the "biggest miss" section.

I could help out with the code if needed, this is literally the best opening preparation software I've seen so far and anyway it can improve will be more than welcome!

**Comment by marcusbuffett** [comment]
Interesting, thanks for the report! I'm in the middle of a large refactor to use a position-based system instead of a line-based system, to support transpositions. I'm hopeful that this bug will just go away as part of that update, should be coming in the next week or so. Sorry you'll have to deal with these outdated answers in the meantime. If it's sufficiently annoying you could export a pgn, import it to a lichess study, remove the outdated lines, then import back to this tool. But you'd have to do that for both sides, and it would eliminate your spaced repetition progress, so probably not worth it. I'll let you know here when the refactor is done

Really appreciate the kind words :) let me know if there's anything you think could make it even better!

**Comment by kenan-rhoton** [comment]
That's awesome! Literally my next request would've been transposition support, so that's about as good as I can ask for! Thanks for all the work :smiley:

**Comment by marcusbuffett** [comment]
Hey, transposition support is in, and I'm pretty sure this should be working now, it works for me at least :) Let me know if you're seeing it still happening.

**Comment by kenan-rhoton** [comment]
At the very least, lines that were deleted prior to the update are still sticking around, but I think new deletions do work. It might be interesting to have the ability to manually delete a line from the edit menu, because right now my only option would be to decide to include a third variation, which would delete both the incorrect and correct lines, forcing me to redo my preparation (which I can do, but I'm just reporting a bug :upside_down_face: )

**Comment by marcusbuffett** [comment]
Ah yeah that's annoying for sure. I'll add a delete button either today or tomorrow, it's long overdue.
